// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/player/join": {
            "post": {
                "description": "player joins game",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "player joins game",
                "parameters": [
                    {
                        "description": "user name, desired capacity",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.PostPlayerJoinHandlerRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/player/status": {
            "post": {
                "description": "sends status info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "sends status info",
                "parameters": [
                    {
                        "description": "user ID",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.PostPlayerStatusHandlerRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "types.PostPlayerJoinHandlerRequest": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "types.PostPlayerStatusHandlerRequest": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "pixel_clash",
	Description:      "This is pixel_clash.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
