basePath: /
definitions:
  types.PostPlayerJoinHandlerRequest:
    properties:
      capacity:
        type: integer
      nickname:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is pixel_clash.
  title: pixel_clash
  version: "1.0"
paths:
  /player/join:
    post:
      consumes:
      - application/json
      description: user joins game
      parameters:
      - description: user name, desired capacity
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/types.PostPlayerJoinHandlerRequest'
      responses: {}
      summary: user joins game
      tags:
      - user
swagger: "2.0"
