basePath: /
definitions:
  types.PostPlayerJoinHandlerRequest:
    properties:
      capacity:
        type: integer
      nickname:
        type: string
    type: object
  types.PostPlayerStatusHandlerRequest:
    properties:
      ID:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is pixel_clash.
  title: pixel_clash
  version: "1.0"
paths:
  /player/join:
    post:
      consumes:
      - application/json
      description: player joins game
      parameters:
      - description: user name, desired capacity
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/types.PostPlayerJoinHandlerRequest'
      responses: {}
      summary: player joins game
      tags:
      - player
  /player/status:
    post:
      consumes:
      - application/json
      description: sends status info
      parameters:
      - description: user ID
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/types.PostPlayerStatusHandlerRequest'
      responses: {}
      summary: sends status info
      tags:
      - player
swagger: "2.0"
